# Generated by Django 4.2.4 on 2023-08-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario',
            new_name='user',
        ),
    ]
