# Generated by Django 4.2.4 on 2023-08-27 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0002_rename_usuario_lineapedido_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
