# Generated by Django 4.2.4 on 2023-08-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
